sudo: required
addons:
  chrome: stable

language: node_js
node_js:
  - "8"

branches:
  only:
    - travis-setup

before_script:
  - npm install -g @angular/cli

script:
  - ng build --prod --aot
  - ng test --browsers ChromeHeadless --watch false --code-coverage

  