version: "3.8"
services:
    otto-ui:
        build: .
        image: sheaffej/otto-ui
        container_name: otto-ui
        # mem_limit: 1g
        restart: always
        # volumes:
        # network_mode: host
        ports:
            - 4200:4200/tcp
